version : '2'

services:
  nodejs:
    build: . 
    image: nodejs
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - '8080:8080'
    container_name: nodejs-express
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/nodejs
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - mydata:/data/db
    networks:
      - node-network
  
volumes:
  mydata:

networks:
  node-network:
    driver: bridge
    